### ISSUE TITLE
running "~/node-bread/bin/bread.js",met error,

### ISSUE THREAD

**Issue by luckypoem** [pvorb/node-bread#13]
hi.
git clone https://github.com/pvorb/node-bread
cd node-bread
npm install

```
as3:~/node-bread# git clone https://github.com/pvorb/vorba.ch vorba.ch-site
as3:~/node-bread# ls
bin       LICENSE       package.json  res   vorba.ch-site
bread.js  node_modules  README.md     test  write.js
as3:~/node-bread# ls bin
bread.js
as3:~/node-bread# chmod 755 ~/node-bread/bin/bread.js
as3:~/node-bread# cd vorba.ch-site
as3:~/node-bread/vorba.ch-site# ls
css.sh  in  js.sh  Makefile  public  README.md  src
(~/node-bread/vorba.ch-site/里面有个隐身的.conf目录，访问https://github.com/pvorb/vorba.ch即可知道）
as3:~/node-bread/vorba.ch-site# ls .conf
api.json    comments.json  modules          search.json  templates
bread.json  ignore.json    properties.json  tags
as3:~/node-bread/vorba.ch-site# npm install mongodb --mongodb:native
as3:~/node-bread/vorba.ch-site# ~/node-bread/bin/bread.js
not ok

/root/node-bread/node_modules/mongodb/lib/mongodb/connection/server.js:336
        throw err;
              ^
MongoError: ns not found
    at Db.wrap (/root/node-bread/node_modules/mongodb/lib/mongodb/db.js:1675:11)
    at null.<anonymous> (/root/node-bread/node_modules/mongodb/lib/mongodb/db.js:808:78)
    at g (events.js:175:14)
    at EventEmitter.emit (events.js:106:17)
    at Db._callHandler (/root/node-bread/node_modules/mongodb/lib/mongodb/db.js:1290:25)
    at /root/node-bread/node_modules/mongodb/lib/mongodb/connection/server.js:329:30
    at MongoReply.parseBody (/root/node-bread/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:118:5)
    at null.<anonymous> (/root/node-bread/node_modules/mongodb/lib/mongodb/connection/server.js:320:22)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/root/node-bread/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:147:13)
as3:~/node-bread/vorba.ch-site# 
```

how to fix it?thank you!

**Comment by pvorb** [comment]
I will have a look at this tomorrow.

**Comment by pvorb** [comment]
When you setup MongoDB for use with bread, you have to first setup the collection specified in `.conf/bread.json` in order to make bread run.

Ensure `mongod` is running, then:

```
$ git clone https://github.com/pvorb/vorba.ch vorba.ch-site
$ cd vorba.ch-site
$ npm install -g bread
$ mongo
MongoDB shell version: x.y.z
connecting to: test
> use vorb_de
switched to db vorb_de
> db.createCollection('docs')
{ "ok": 1 }
> exit
bye
$ bread
```

You don't need to install mongodb via npm. It's done by installing bread itself (`npm install -g bread` will do the magic).

I hope that solves your issue. Please reopen if not.

**Comment by luckypoem** [comment]
hi.
i operated the mongodb thing,but then still met error.
how to fix it?tks!

```
as3:~/node-bread/vorba.ch-site# ~/node-bread/bin/bread.js
Beginning to bake /root/node-bread/vorba.ch-site/in.
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
as3:~/node-bread/vorba.ch-site# ls ~/npm
bin  lib
as3:~/node-bread/vorba.ch-site# ~/npm/bin/bread
Beginning to bake /root/node-bread/vorba.ch-site/in.
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
as3:~/node-bread/vorba.ch-site#
```

**Comment by luckypoem** [comment]
hi.
any solutions?

**Comment by pvorb** [comment]
I'm sorry, but I can't reproduce the error.

**Comment by pvorb** [comment]
Please try to follow the steps from [above](#issuecomment-39889912) from scratch if you haven't already done so. Probably you did something I can't see yet.

**Comment by luckypoem** [comment]
hi.
can give another option of just using filesystem instead of mongodb to store posts?that will be simpler and is REALLY STATIC.
TKS.

**Comment by pvorb** [comment]
I wanted to remove the mongodb dependency years ago, but I don't have the time to do so.

**Comment by luckypoem** [comment]
hi.
today i tried ur app again.
but this time the error is different.
root@as3:~/node-bread# node bin/bread.js

/root/node-bread/bin/bread.js:13
    throw err;
          ^
Error: No configuration directory found.
    at stat (/root/node-bread/node_modules/confdir/confdir.js:21:22)
    at Object.oncomplete (fs.js:107:15)
root@as3:~/node-bread#
HOW TO FIX IT?TKS.

and accidentally,i found the root dir of the static site:
root@as3:~/node-bread# ls
bin       LICENSE       package.json  res   vorba.ch-site
bread.js  node_modules  README.md     test  write.js
root@as3:~/node-bread# cd vorba.ch-site
root@as3:~/node-bread/vorba.ch-site# ls
css.sh  js.sh  Makefile  private  public  README.md  src
root@as3:~/node-bread/vorba.ch-site# cd public
root@as3:~/node-bread/vorba.ch-site/public# ls
2011           favicon.ico                  index.html        res
2012           feed.xml                     license           robots.txt
2013           google6e57b18a7e9f5804.html  markdown.de.html  subscription.html
2014           index-2.html                 markdown.en.html  tag
archive.html   index-3.html                 public.asc        vorb.de.html
blogroll.html  index-4.html                 pvorb.html        work
contact.html   index-5.html                 pvorb.png
root@as3:~/node-bread/vorba.ch-site/public# nohup Rwebserver 32783 > /dev/null &

visit http://as3.brite.biz:32783/ ,i can see ur site,but i just can't update it.
